### PR TITLE
Added Chantler data

### PR DESCRIPTION
**Pull request by EmCeBeh**
Added chantler table data and changed the default database path in atoms.py

### CODE REVIEW

**Comment by dschick** [comment]
please check `flake8` and `pytest`

**Comment by dschick** [comment]
The pytest seems to fail. Please check the log file from Travis CI
Travis seems to have problems to read the new chantler files

**Comment by EmCeBeh** [comment]
Server-side issue:
locally pytest works fine. Travis does not find the file
`File /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/udkm1Dsim/parameters/atomicFormFactors/chantler/dy.cf not found!`...

naming it `dy.cf` or `Dy.cf`does not make a difference.

**Comment by dschick** [comment]
now I found the problem. the cf files are not properly installed via pip since the file type is not added in the `setup.py` file.
I will merge the PR and add the change in a separat commit. thanks for the work

**Pull request merged**
